{% set version = "0.1" %}

package:
  name: kmdiff
  version: {{ version }}

source:
  git_url: https://github.com/tlemane/kmdiff

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake
    - gsl
    - openblas
    - lapack

  host:
    - zlib

  run:
    - zlib
    - gsl
    - openblas
    - lapack
    - kmtricks>=0.0.6
    - python>=3.6
    - bbmap>=38.90
    - samtools>=1.12
    - bedtools>=2.30
    - abyss>=2.3.1

about:
  home: https://github.com/tlemane/kmdiff
  license: AGPL-3.0
  doc_url: https://github.com/tlemane/kmdiff

extra:
  recipe-maintainers:
    - tlemane