{% set version = "0.1" %}

package:
  name: kmdiff
  version: {{ version }}

source:
  git_url: https://github.com/tlemane/kmdiff

requirements:
  build:
    - {{ compiler('cxx') }}
    - make
    - cmake

  host:
    - zlib

  run:
    - zlib
    - kmtricks>=0.0.6
    - python>=3.6
    - bbmap>=38.90

about:
  home: https://github.com/tlemane/kmdiff
  license: AGPL-3.0
  doc_url: https://github.com/tlemane/kmdiff

extra:
  recipe-maintainers:
    - tlemane