name: osx

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docker/**'
      - 'conda/**'
      - 'scripts/**'
      - '.gitignore'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install dependencies
        run: brew install gsl lapack openblas bzip2 zlib

      - name: Env
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCOMPILE_TESTS=ON -DMAKE_PACKAGE=ON -DWITH_POPSTRAT=OFF

      - name: Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --config $BUILD_TYPE -j2

      - name: Test
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ctest -C $BUILD_TYPE --verbose

      - name: Package
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: make package

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Auto release
        if: |
          github.ref == 'refs/heads/master' &&
          contains(github.event.head_commit.message, '[auto]')
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          echo $GH_TOKEN
          ls $GITHUB_WORKSPACE
          pwd
          python -m pip install --upgrade pip
          pip install PyGithub
          python3 $GITHUB_WORKSPACE/scripts/auto_release.py ${{runner.workspace}}/build